# Generated by Django 5.2.16 on 2026-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Indicates whether this staff member can be assigned to teach.'),
        ),
    ]
