# Generated by Django 5.2.16 on 2026-07-22 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subjectoffering_teacherassignment_and_more'),
        ('finance', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinvoice",
            name="billing_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
            ),
        ),

        migrations.AddConstraint(
            model_name="studentinvoice",
            constraint=models.UniqueConstraint(
                condition=~models.Q(
                    billing_key=""
                ),
                fields=(
                    "school",
                    "billing_key",
                ),
                name=(
                    "unique_invoice_billing_key_"
                    "per_school"
                ),
            ),
        ),
    ]
