# Generated by Django 5.2.16 on 2026-07-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_studentinvoice_unique_invoice_billing_key_per_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialadjustment',
            options={'permissions': [('approve_financial_adjustment', 'Can approve discounts, scholarships and waivers'), ('reverse_financial_adjustment', 'Can reverse financial adjustments')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at'], 'permissions': [('record_student_payment', 'Can record student payments'), ('reverse_student_payment', 'Can reverse student payments')]},
        ),
        migrations.AlterModelOptions(
            name='studentinvoice',
            options={'ordering': ['-issue_date', '-created_at'], 'permissions': [('issue_student_invoice', 'Can issue student invoices'), ('void_student_invoice', 'Can void student invoices')]},
        ),
    ]
