# Generated by Django 5.2.16 on 2026-08-18 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_admission_prefix'),
        ('students', '0002_studentimportbatch_studentimportrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmissionSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'year'), name='unique_student_admission_sequence_per_school_year')],
            },
        ),
    ]
