# Generated by Django 5.2.16 on 2026-07-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeband',
            name='is_pass',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='is_pass',
            field=models.BooleanField(default=True),
        ),
    ]
