# Generated by Django 5.2.16 on 2026-07-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_gradeband_is_pass_subjectresult_is_pass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectresult',
            options={'permissions': [('submit_subject_result', 'Can submit subject results'), ('approve_subject_result', 'Can approve subject results'), ('publish_subject_result', 'Can publish subject results')]},
        ),
    ]
