# Generated by Django 5.2.16 on 2026-07-22 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('active_student_limit', models.PositiveIntegerField(default=200)),
                ('admin_user_limit', models.PositiveIntegerField(default=5)),
                ('features', models.JSONField(blank=True, default=dict, help_text="Feature entitlement map. Example: {'finance': true, 'payroll': false}")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('payment_due', 'Payment Due'), ('grace_period', 'Grace Period'), ('read_only', 'Read Only'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('grace_period_end', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='schools.school')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
