# Generated by Django 5.2.16 on 2026-07-22 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_subjectoffering_teacherassignment_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('failed_subjects', models.PositiveSmallIntegerField(default=0)),
                ('recommendation', models.CharField(choices=[('promote', 'Promote'), ('repeat', 'Repeat'), ('demote', 'Demote'), ('review', 'Manual Review'), ('graduate', 'Graduate')], max_length=20)),
                ('reasons', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_evaluations', to='academics.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_decision', models.CharField(choices=[('promote', 'Promote'), ('repeat', 'Repeat'), ('demote', 'Demote'), ('graduate', 'Graduate'), ('review', 'Manual Review')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_decisions_approved', to=settings.AUTH_USER_MODEL)),
                ('resulting_enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_promotion_decision', to='academics.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('target_class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_decisions_targeting', to='academics.classsection')),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='promotions.promotionevaluation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('version', models.PositiveIntegerField(default=1)),
                ('minimum_overall_average', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('subject_pass_mark', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('maximum_failed_subjects', models.PositiveSmallIntegerField(default=2)),
                ('minimum_attendance_percentage', models.DecimalField(blank=True, decimal_places=2, default=75, max_digits=5, null=True)),
                ('demotion_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. If the annual average falls below this value, the system may recommend demotion.', max_digits=5, null=True)),
                ('failure_action', models.CharField(choices=[('repeat', 'Repeat'), ('review', 'Manual Review')], default='repeat', max_length=20)),
                ('require_all_terms', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_policies', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_policies', to='academics.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
            ],
        ),
        migrations.AddField(
            model_name='promotionevaluation',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='promotions.promotionpolicy'),
        ),
        migrations.CreateModel(
            name='PromotionSubjectRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_rules', to='promotions.promotionpolicy')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_rules', to='academics.subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='promotionpolicy',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'class_level', 'version'), name='unique_promotion_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='promotionpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'academic_year', 'class_level'), name='one_active_promotion_policy_per_level_year'),
        ),
        migrations.AddConstraint(
            model_name='promotionevaluation',
            constraint=models.UniqueConstraint(fields=('policy', 'enrollment'), name='one_promotion_evaluation_per_policy_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='promotionsubjectrule',
            constraint=models.UniqueConstraint(fields=('policy', 'subject'), name='unique_promotion_subject_rule'),
        ),
    ]
