# Generated by Django 5.2.16 on 2026-07-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotiondecision',
            options={'permissions': [('approve_promotion_decision', 'Can approve promotion decisions'), ('execute_promotion_decision', 'Can execute promotion decisions')]},
        ),
        migrations.AlterModelOptions(
            name='promotionevaluation',
            options={'permissions': [('run_promotion_evaluation', 'Can run promotion evaluation')]},
        ),
    ]
