# Generated by Django 5.2.16 on 2026-07-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-attendance_date'], 'permissions': [('submit_attendance', 'Can submit attendance'), ('lock_attendance', 'Can lock attendance')]},
        ),
    ]
