# Generated by Django 5.2.16 on 2026-07-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': [('manage_school_settings', 'Can manage school settings'), ('manage_school_users', 'Can manage school users'), ('manage_school_roles', 'Can manage school roles and permissions')]},
        ),
    ]
