# Generated by Django 5.2.16 on 2026-07-23 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('login_background_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#111827', max_length=20)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('accent_color', models.CharField(default='#2563EB', max_length=20)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
