# Generated by Django 5.2.16 on 2026-08-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schoolbranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admission_prefix',
            field=models.CharField(blank=True, help_text='Prefix used for automatically generated student admission numbers.', max_length=10),
        ),
    ]
